services:
  valhalla:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    ports:
      - "8002:8002"
    volumes:
      - ./valhalla.json:/custom_files/valhalla.json:ro
      - ./valhalla_tiles:/custom_files/valhalla_tiles
    entrypoint: ["valhalla_service"]
    command: ["/custom_files/valhalla.json", "1"]
