services:
  valhalla:
    image: gisops/valhalla:latest
    ports:
      - "8002:8002"
    volumes:
      - ./valhalla.json:/custom_files/valhalla.json:ro
      - ./valhalla_tiles:/custom_files/valhalla_tiles
    command: ["valhalla_service", "/custom_files/valhalla.json", "1"]
